### PR TITLE
Evaluator fix

### PR DESCRIPTION
**Pull request by lisicky**
## Summary

This pull request introduces several improvements and fixes to the `sidan-csl-rs` crate, particularly in the areas of transaction script evaluation and network type handling. The changes include passing references instead of values, adding error text for better debugging, fixing network deserialization, and introducing new tests to ensure the reliability of these changes.

### Feature Change

- [x] WASM `sidan-csl-rs` - Feature update

### Maintenance

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Code refactoring (improving code quality without changing its behavior)

## Checklist

- [x] My code is appropriately commented and includes relevant documentation, if necessary
- [x] I have added tests to cover my changes, if necessary
- [x] I have updated the documentation, if necessary
- [x] All new and existing tests pass
- [x] Both rust and wasm build pass

## Additional Information

The main changes in this pull request include:

1. Modified `evaluate_tx_scripts_js` function to pass `resolved_utxos` and `additional_txs` by reference, improving memory management.
2. Improved error handling and messages in UTXO and network deserialization.
3. Implemented `TryFrom<String>` for `Network` enum to enhance network type parsing.
4. Added `as_ref_vec` method to `JsVecString` for better reference handling.
5. Introduced new tests for network type decoding and UTXO/TX evaluation to ensure the reliability of these changes.

### CODE REVIEW

**Comment by HinsonSIDAN** [comment]
image

@lisicky any ideas what this linting about? actually probably can ignore for now but want to see if you have thoughts

**Comment by lisicky** [comment]
> image
> @lisicky any ideas what this linting about? actually probably can ignore for now but want to see if you have thoughts

@HinsonSIDAN it’s about that the function is not used. We can drop this function, but I would left it for future

**Comment by HinsonSIDAN** [comment]
Ok i make it a publicly accessible function for now.

**Review by HinsonSIDAN — APPROVED** [review]
lgtm

**Pull request merged**
